spring:
  application:
    name: scw-user
  datasource:
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.188.147
    port: 6379


server:
  port: 7000

logging:
  file:
    path: D:\log
  level:
    com:
      offcn: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  appcode: f44b9437185349ad89f5504b8e01f393