spring:
  application:
    name: scw-order
  datasource:
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.188.147
    port: 6379


server:
  port: 9000

logging:
  file:
    path: D:\log
  level:
    com:
      offcn: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tPz9w7sN7BgUQQaKdey
  accessKeySecret: gvNaxQPg46t1MhZu4oxvi1qdibG6ny
  bucketName: junqi-offcn
  bucketurl: https://junqi-offcn.oss-cn-beijing.aliyuncs.com
